name: "EK HTMLCov"
description: "Action for generating HTML files with Go coverage info"
author: "ESSENTIALKAOS"

branding:
  icon: 'trending-up'
  color: 'white'

inputs:
  profile:
    description: "Path to coverage profile"
    required: true

  path:
    description: "Path to directory with sources"
    required: true

  output:
    description: "Output artifact name"
    required: false
    default: "Coverage"

  version:
    description: "Version of HTMLCov"
    required: false
    default: "1.1.1"

  retention:
    description: "Retention in days"
    required: false
    default: 3

runs:
  using: "composite"
  steps:
    - id: htmlcov-install
      name: Install HTMLCov
      shell: bash
      run: |
        # [htmlcov-install]

        echo -e "::group::\033[34mBuilding HTMLCov…\033[0m"

        go install github.com/essentialkaos/htmlcov@v${{inputs.version}}

        mkdir -p ~/.cache
        cp "$(which htmlcov)" ~/.cache/htmlcov

        echo "::endgroup::"

    - id: htmlcov-version-print
      name: Print HTMLCov version info
      shell: bash
      run: |
        # [htmlcov-version-print]

        echo -e "::group::\033[34mPrint HTMLCov version…\033[0m"
        ~/.cache/htmlcov --version
        echo "::endgroup::"

    - id: htmlcov-generate
      name: Generate HTML
      shell: bash
      run: |
        # [htmlcov-generate]

        cd ${{inputs.path}}
        ~/.cache/htmlcov ${{inputs.profile}}

    - id: htmlcov-upload
      name: Upload HTML artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.output}}
        path: ${{inputs.path}}/coverage.html
        retention-days: ${{inputs.retention}}
